rwc/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include(("webapp.urls", "plants"), namespace="webapp")),
]

webapp/urls.py
from django.urls import path

from webapp import views


urlpatterns = [
    path("server_detail/<pk>/", views.ServerDetail.as_view(), name="ServerDetail"),
    path("create_server/", views.ServerCreate.as_view(), name="ServerCreate"),
    path("update_server/<pk>/", views.ServerUpdate.as_view(), name="ServerUpdate"),
    path("delete_server/<pk>/", views.ServerUpdate.as_view(), name="ServerDelete"),
    path("", views.ServerIndex.as_view(), name="ServerIndex"),
]

webapp/models.py
from django.db import models
from django.urls import reverse
from django.utils.translation import gettext_lazy as _


class RedisServer(models.Model):
    name = models.CharField(
        max_length=255, unique=True, help_text=_("A name to identify the server")
    )
    host = models.CharField(max_length=255, help_text=_("redis server host"))
    port = models.PositiveIntegerField(default=6379, help_text=_("redis server port"))
    password = models.CharField(max_length=255, blank=True, help_text=_("redis server host"))

    class Meta:
        ordering = ("-name",)

    def get_absolute_url(self):
        return reverse("webapp:ServerDetail", kwargs={"pk": self.pk})

    def __str__(self) -> str:
        return self.name

webapp/views.py
from typing import List

from django.urls import reverse_lazy
from django.db.models import QuerySet
from django.views import generic
from webapp.models import RedisServer

CRUD_FIELDS: List[str] = ["name", "host", "password", "port", "db"]


class ServerIndex(generic.ListView):
    template_name = "webapp/homepage.html"
    context_object_name = "servers"
    queryset: QuerySet = RedisServer.objects.all()


class ServerCreate(generic.CreateView):
    template_name = "webapp/create_server.html"
    model = RedisServer
    fields = CRUD_FIELDS
    success_url = reverse_lazy("webapp:ServerIndex")


class ServerDetail(generic.DeleteView):
    model = RedisServer
    context_object_name = "server"
    template_name = "webapp/server_detail.html"


class ServerUpdate(generic.UpdateView):
    model = RedisServer
    fields = CRUD_FIELDS
    template_name_suffix = "_update_form"


class ServerDelete(generic.DeleteView):
    model = RedisServer
    success_url = reverse_lazy("home-page")


class Connect(generic.View):
    def get(self, request, **kwargs):
        return

webapp/templates/base.html
<!DOCTYPE html>
<html>

<head>
    <meta charset='utf-8'>
    <meta http-equiv='X-UA-Compatible' content='IE=edge'>
    <title>Redis Web View - {% block title %}{%endblock title%}</title>
    <meta name='viewport' content='width=device-width, initial-scale=1'>
    <link rel='stylesheet' type='text/css' media='screen' href='main.css'>
    <script src='main.js'></script>
</head>

<body>
    {% block content %}{% endblock %}
</body>

</html>

webapp/templates/webapp/create_server.html
{% extends 'base.html' %}

{% block content %}
<form method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Save">
</form>
{% endblock %}

webapp/templates/webapp/homepage.html
{% extends 'base.html' %}
{% block content %}
<a href="{% url 'webapp:ServerCreate' %}">Create a new redis server</a>

<table style="width: 100%;">
    <tr>
        <th>server name</th>
        <th>host</th>
        <th>passowrd</th>
        <th>db</th>
    </tr>
    {% for server in servers %}
    <tr>
        <td>
            <a href="{% url 'webapp:ServerDetail' server.pk %}">{{ server.name }}</a>
        </td>
        <td>{{ server.host }}</td>
        <td>****password</td>
        <td>{{ server.db }}</td>
    </tr>
    {% endfor %}
</table>
{% endblock %}

webapp/templates/webapp/server_confirm_delete.html
{% extends 'base.html' %}

{ % block content %}
<form method="post">{% csrf_token %}
    <p>Are you sure you want to delete "{{ object }}"?</p>
    <input type="submit" value="Confirm Delete">
</form>
{ % endblock %}

webapp/templates/webapp/server_detail.html
{% extends 'base.html' %}

{% block content %}
<p>
    {{ server.name }}
    {{ server.host }}
</p>
{% endblock %}

webapp/templates/webapp/server_form.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<body>
    <form method="post">{% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Save">
    </form>
</body>

</html>

webapp/templates/webapp/server_update_form.html
{% extends 'base.html' %}
{% block content %}
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Update">
</form>
{% endblock %}